### ISSUE TITLE
migration of Jenkins setups to Jenkins X

### ISSUE THREAD

**Issue by 2020testuser** [jenkins-x/enhancements#27]
Hi,
Since, most of the companies are currently using Jenkins (or Jenkins2) , it would be really very useful if there is  a migration document which covers from migrating from Jenkins and Jenkins2 to JenkinsX. Let me know whether I need to submit any doc. with details for this. Thanks in advance!

**Comment by vfarcic** [comment]
@abayer write a script that transforms pipeline definitions from Static Jenkins X to Serverless (Tekton), but that's probably not what is needed.

I don't think that we can migrate jobs automatically.

What I would suggest is to start working on a set of pattern. If you have this in Jenkins file, the equivalent in JX is that. We probably do not need to have it completed at once. We can start with a few examples, and grow them over time.

What do you think? Would you be interested in making the first draft @2020testuser?

**Comment by 2020testuser** [comment]
@vfarcic - Thanks for the info. I thought that there is no migration tool/component and wanted to confirm before I proceed. 
I'm not an expert in Jenkins(or Jenkins2) and didn't create the pipelines. However, I'll write a high-level draft and send it. Others can add to it when they review. Thanks!

**Comment by jstrachan** [comment]
maybe as part of the [Jenkins 3.x effort](https://github.com/jenkins-x/enhancements/issues/36) we may want to look at how to 

* migrate Jenkins servers into Jenkins X via the [Jenkins Operator](https://github.com/jenkinsci/kubernetes-operator) so that they can be managed by Jenkins X via GitOps.
* reuse the improvements around integration with Jenkins X and Jenkins + Tekton for importing jobs and triggering pipelines so that Jenkins X 3.x can be used for both tekton and any Jenkins Server
